import { AdminProduct, AuthCode, DashboardMetric } from '@/types/admin';

export const mockDashboardMetrics: DashboardMetric[] = [
  { label: 'Total Products', value: '12', trend: '+2 this month', isPositive: true },
  { label: 'Inventory Count', value: '1,420', trend: '-15% vs last month', isPositive: false },
  { label: 'Verification Codes', value: '25,000', trend: '10k unused', isPositive: true },
  { label: 'Total Scans', value: '8,432', trend: '+1.2k this week', isPositive: true },
];

export const mockProducts: AdminProduct[] = [
  {
    id: 'prod_1',
    slug: 'kyrox-mass-gainer-chocolate',
    name: 'Kyrox Mass Gainer',
    category: 'mass-gainer',
    categoryLabel: 'Mass Gainer',
    flavor: 'Double Rich Chocolate',
    weight: '3 kg',
    highlights: ['High Protein', 'Massive Calorie Surplus'],
    image: '/images/products/mass-gainer-choc.png',
    gallery: [],
    description: 'Premium mass gainer formulated for hard gainers.',
    benefits: ['Rapid Muscle Growth', 'Enhanced Recovery'],
    nutritionFacts: [{ label: 'Calories', value: '1250' }, { label: 'Protein', value: '50g' }],
    ingredients: ['Whey Protein Concentrate', 'Maltodextrin', 'Cocoa Powder'],
    usageInstructions: ['Mix 2 scoops with water or milk'],
    proteinGrams: 50,
    calories: 1250,
    releaseOrder: 1,
    isFeatured: true,
    stockQuantity: 150,
    status: 'In Stock',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod_2',
    slug: 'kyrox-whey-isolate-vanilla',
    name: 'Kyrox Whey Isolate',
    category: 'whey-protein',
    categoryLabel: 'Whey Protein',
    flavor: 'Vanilla Ice Cream',
    weight: '2 kg',
    highlights: ['Fast Absorption', 'Zero Sugar'],
    image: '/images/products/whey-isolate-vanilla.png',
    gallery: [],
    description: 'Purest form of whey protein isolate for lean muscle.',
    benefits: ['Lean Muscle Support', 'Fast Recovery'],
    nutritionFacts: [{ label: 'Calories', value: '110' }, { label: 'Protein', value: '25g' }],
    ingredients: ['Whey Protein Isolate', 'Natural Flavors'],
    usageInstructions: ['Mix 1 scoop post-workout'],
    proteinGrams: 25,
    calories: 110,
    releaseOrder: 2,
    isFeatured: false,
    stockQuantity: 10,
    status: 'Low Stock',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod_3',
    slug: 'kyrox-pre-workout-fruit-punch',
    name: 'Kyrox Pre-Workout',
    category: 'whey-protein', // Assuming categories are limited, we'll map pre-workout here for now or add to types later
    categoryLabel: 'Pre-Workout',
    flavor: 'Fruit Punch',
    weight: '300 g',
    highlights: ['Explosive Energy', 'Laser Focus'],
    image: '/images/products/pre-workout-fruit.png',
    gallery: [],
    description: 'High stim pre-workout for intense training sessions.',
    benefits: ['Energy Boost', 'Increased Endurance'],
    nutritionFacts: [{ label: 'Calories', value: '5' }],
    ingredients: ['Caffeine Anhydrous', 'Beta-Alanine', 'L-Citrulline'],
    usageInstructions: ['Mix 1 scoop 30 mins before workout'],
    proteinGrams: 0,
    calories: 5,
    releaseOrder: 3,
    isFeatured: false,
    stockQuantity: 0,
    status: 'Out of Stock',
    updatedAt: new Date().toISOString(),
  }
];

export const mockAuthCodes: AuthCode[] = [
  {
    id: 'auth_1',
    productId: 'prod_1',
    productName: 'Kyrox Mass Gainer',
    uniqueCode: 'KRG-8X9-MN2',
    batchNumber: 'B-2026-05',
    scanCount: 1,
    status: 'Valid',
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    lastScannedAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'auth_2',
    productId: 'prod_2',
    productName: 'Kyrox Whey Isolate',
    uniqueCode: 'KWV-2A4-ZZ9',
    batchNumber: 'B-2026-04',
    scanCount: 0,
    status: 'Valid',
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
  },
  {
    id: 'auth_3',
    productId: 'prod_1',
    productName: 'Kyrox Mass Gainer',
    uniqueCode: 'KRG-SUS-P1C',
    batchNumber: 'B-2026-05',
    scanCount: 15,
    status: 'Suspicious',
    createdAt: new Date(Date.now() - 86400000 * 30).toISOString(),
    lastScannedAt: new Date().toISOString(),
  },
  {
    id: 'auth_4',
    productId: 'prod_3',
    productName: 'Kyrox Pre-Workout',
    uniqueCode: 'KPW-INV-L1D',
    batchNumber: 'B-2026-01',
    scanCount: 50,
    status: 'Invalid',
    createdAt: new Date(Date.now() - 86400000 * 100).toISOString(),
    lastScannedAt: new Date(Date.now() - 86400000).toISOString(),
  }
];

import { AuthCodeRecord } from '@/types/auth';

export const mockAuthCodeRecords: AuthCodeRecord[] = [
  {
    id: 'rec_1',
    product_id: 'prod_1',
    code: 'KYX-MG-8X92P1',
    batch_number: 'B-2026-05',
    scan_count: 1,
    first_scanned_at: new Date(Date.now() - 3600000).toISOString(),
    created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
    is_active: true,
  },
  {
    id: 'rec_2',
    product_id: 'prod_2',
    code: 'KYX-WP-A7KQ21',
    batch_number: 'B-2026-04',
    scan_count: 0,
    first_scanned_at: null,
    created_at: new Date(Date.now() - 86400000 * 10).toISOString(),
    is_active: true,
  },
  {
    id: 'rec_3',
    product_id: 'prod_1',
    code: 'KYX-MG-DUP123',
    batch_number: null,
    scan_count: 15,
    first_scanned_at: new Date(Date.now() - 86400000 * 20).toISOString(),
    created_at: new Date(Date.now() - 86400000 * 30).toISOString(),
    is_active: true,
  },
  {
    id: 'rec_4',
    product_id: 'prod_3',
    code: 'KYX-PW-FAKE99',
    batch_number: 'B-2026-01',
    scan_count: 50,
    first_scanned_at: new Date(Date.now() - 86400000 * 90).toISOString(),
    created_at: new Date(Date.now() - 86400000 * 100).toISOString(),
    is_active: false,
  }
];
